In [2]:
!pip install scikit-learn pandas numpy

Requirement already satisfied: scikit-learn in c:\users\abdul\appdata\local\programs\python\python313\lib\site-packages (1.6.1)
Requirement already satisfied: pandas in c:\users\abdul\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: numpy in c:\users\abdul\appdata\local\programs\python\python313\lib\site-packages (2.2.1)
Requirement already satisfied: scipy>=1.6.0 in c:\users\abdul\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.15.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\abdul\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\abdul\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\abdul\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\abdul\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\abdul\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\abdul\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: C:\Users\abdul\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

df = pd.read_csv(r"..\dataset\Cleaned_data_for_model.csv")

del df["purpose"]
del df['Unnamed: 0']

df

,property_type,price,location,city,baths,bedrooms,Area_in_Marla
0,Flat,10000000,G-10,Islamabad,2,2,4.0
1,Flat,6900000,E-11,Islamabad,3,3,5.6
2,House,16500000,G-15,Islamabad,6,5,8.0
3,House,43500000,Bani Gala,Islamabad,4,4,40.0
4,House,7000000,DHA Defence,Islamabad,3,3,8.0
...,...,...,...,...,...,...,...
99494,Flat,7500000,Bahria Town Karachi,Karachi,3,3,8.0
99495,House,8800000,Bahria Town Karachi,Karachi,4,3,8.0
99496,House,14000000,Bahria Town Karachi,Karachi,3,3,8.0
99497,House,14000000,Bahria Town Karachi,Karachi,4,4,14.0
99498,House,9000000,Bahria Town Karachi,Karachi,3,3,9.4

In [4]:
df.describe()

              price         baths      bedrooms  Area_in_Marla
count  9.949900e+04  99499.000000  99499.000000   99499.000000
mean   1.037592e+07      3.530106      3.350737       8.757479
std    1.066000e+07      1.474217      1.255913       7.466471
min    1.550000e+04      1.000000      0.000000       0.000000
25%    1.500000e+05      2.000000      2.000000       4.800000
50%    7.500000e+06      3.000000      3.000000       6.700000
75%    1.550000e+07      5.000000      4.000000      10.000000
max    4.490000e+07      7.000000      6.000000     194.000000

In [5]:
pd.isna(df)

       property_type  price  location   city  baths  bedrooms  Area_in_Marla
0              False  False     False  False  False     False          False
1              False  False     False  False  False     False          False
2              False  False     False  False  False     False          False
3              False  False     False  False  False     False          False
4              False  False     False  False  False     False          False
...              ...    ...       ...    ...    ...       ...            ...
99494          False  False     False  False  False     False          False
99495          False  False     False  False  False     False          False
99496          False  False     False  False  False     False          False
99497          False  False     False  False  False     False          False
99498          False  False     False  False  False     False          False

[99499 rows x 7 columns]

In [6]:
pd.isnull(df)

       property_type  price  location   city  baths  bedrooms  Area_in_Marla
0              False  False     False  False  False     False          False
1              False  False     False  False  False     False          False
2              False  False     False  False  False     False          False
3              False  False     False  False  False     False          False
4              False  False     False  False  False     False          False
...              ...    ...       ...    ...    ...       ...            ...
99494          False  False     False  False  False     False          False
99495          False  False     False  False  False     False          False
99496          False  False     False  False  False     False          False
99497          False  False     False  False  False     False          False
99498          False  False     False  False  False     False          False

[99499 rows x 7 columns]

In [7]:
cols_to_fill = ['price', 'baths', 'bedrooms', 'Area_in_Marla']
df[cols_to_fill] = df[cols_to_fill].fillna(df[cols_to_fill].mean())

In [8]:
cols_to_fill_with_mod = ['property_type', 'location', 'city']
df[cols_to_fill_with_mod] = df[cols_to_fill_with_mod].fillna(df[cols_to_fill_with_mod].mode().iloc[0])

In [9]:
df['property_type'] = df['property_type'].map({'Flat':0, "House": 1})

In [22]:
from sklearn.preprocessing import LabelEncoder

# Correct approach: Separate encoders per column
location_encoder = LabelEncoder()
city_encoder = LabelEncoder()

df['location'] = location_encoder.fit_transform(df['location'])
df['city'] = city_encoder.fit_transform(df['city'])

In [23]:
df

       property_type     price  location  city  baths  bedrooms  Area_in_Marla
0                0.0  10000000       452     1      2         2            4.0
1                0.0   6900000       382     1      3         3            5.6
2                1.0  16500000       457     1      6         5            8.0
3                1.0  43500000       198     1      4         4           40.0
4                1.0   7000000       327     1      3         3            8.0
...              ...       ...       ...   ...    ...       ...            ...
99494            0.0   7500000       189     2      3         3            8.0
99495            1.0   8800000       189     2      4         3            8.0
99496            1.0  14000000       189     2      3         3            8.0
99497            1.0  14000000       189     2      4         4           14.0
99498            1.0   9000000       189     2      3         3            9.4

[99499 rows x 7 columns]

In [24]:
has_nulls = df.isnull().values.any()
print("Does the dataset have any null values?", has_nulls)

Does the dataset have any null values? False

In [25]:
# Counts null values in each column
null_counts = df.isnull().sum()
print("Null values per column:\n", null_counts)

Null values per column:
 property_type    0
price            0
location         0
city             0
baths            0
bedrooms         0
Area_in_Marla    0
dtype: int64

In [26]:
# Get rows where ANY column has a null value
rows_with_nulls = df[df.isnull().any(axis=1)]
print("Rows with null values:\n", rows_with_nulls)

Rows with null values:
 Empty DataFrame
Columns: [property_type, price, location, city, baths, bedrooms, Area_in_Marla]
Index: []

In [27]:
df['property_type'] = df['property_type'].fillna(2)
rows_with_nulls = df[df.isnull().any(axis=1)]
print("Rows with null values:\n", rows_with_nulls)

Rows with null values:
 Empty DataFrame
Columns: [property_type, price, location, city, baths, bedrooms, Area_in_Marla]
Index: []

In [28]:
# Counts null values in each column
null_counts = df.isnull().sum()
print("Null values per column:\n", null_counts)

Null values per column:
 property_type    0
price            0
location         0
city             0
baths            0
bedrooms         0
Area_in_Marla    0
dtype: int64

In [29]:
from sklearn.model_selection import train_test_split

X = df.drop('price', axis=1)
y = df["price"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [30]:
from sklearn.neighbors import KNeighborsRegressor

knn = KNeighborsRegressor(n_neighbors=5)

knn.fit(X_train, y_train)

KNeighborsRegressor()

In [31]:
from joblib import dump

# Save the KNN model
dump(knn, 'knn_model_house_price_estimator.joblib')

['knn_model_house_price_estimator.joblib']

In [32]:
from joblib import dump

# Save the LabelEncoder (replace 'le' with your encoder variable)
dump(location_encoder, 'label_encoder_property.joblib')
dump(city_encoder, 'label_encoder_location.joblib')

['label_encoder_location.joblib']